"""users table

Revision ID: e3a0923e6020
Revises: 
Create Date: 2019-08-22 17:50:47.512532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a0923e6020'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equation', sa.String(length=256), nullable=True),
    sa.Column('invoice', sa.String(length=257), nullable=True),
    sa.Column('r_hash', sa.String(length=56), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_equation'), 'user', ['equation'], unique=False)
    op.create_index(op.f('ix_user_invoice'), 'user', ['invoice'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invoice'), table_name='user')
    op.drop_index(op.f('ix_user_equation'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
